version: '3.8'

services:
  haproxy:
    image: haproxy:2.8
    container_name: haproxy_lb
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy-scale.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx
    networks:
      - scalenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    networks:
      scalenet:
        aliases:
          - nginx-backend

  mysql:
    image: mysql:8.0
    container_name: mysql_scale
    environment:
      MYSQL_ROOT_PASSWORD: naver123
      MYSQL_DATABASE: testdb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scalenet

networks:
  scalenet:
    driver: bridge