apiVersion: 1

groups:
  - name: critical_alerts
    folder: alerts
    interval: 30s
    rules:
      - uid: service_down
        title: Critical Service Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job=~"nginx|haproxy"} == 0
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: Critical service {{ $labels.job }} is down
          summary: Service Down Alert
        labels:
          severity: critical

      - uid: high_resource_usage
        title: High Resource Usage
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80) OR ((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85)
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: System resources are critically high
          summary: High Resource Usage
        labels:
          severity: warning

      - uid: container_issues
        title: Container Resource Issues
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (rate(container_cpu_usage_seconds_total{name!=""}[2m]) * 100 > 80) OR (rate(container_start_time_seconds{name!=""}[10m]) > 0)
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: Container {{ $labels.name }} has resource issues
          summary: Container Alert
        labels:
          severity: warning